include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "benchmarks/**"
    - "tool/**"

linter:
  rules:
    avoid_print: false
    avoid_returning_this: false
    discarded_futures: false
    public_member_api_docs: false
