import 'dart:io';

import 'package:ffigen/ffigen.dart';

void main(List<String> args) {
  final root = Platform.script.resolve('../');
  const names = {
    'odbc_columnar_decompress',
    'odbc_columnar_decompress_free',
    'odbc_columnar_decompress_release',
  };
  FfiGenerator(
    headers: Headers(
      entryPoints: [root.resolve('native/odbc_engine/include/odbc_engine.h')],
    ),
    functions: Functions(
      include: (declaration) => names.contains(declaration.originalName),
      includeSymbolAddress: (declaration) =>
          declaration.originalName == 'odbc_columnar_decompress_release',
    ),
    output: Output(
      dartFile: root.resolve(
        'lib/infrastructure/native/bindings/columnar_decompress.g.dart',
      ),
      style: const DynamicLibraryBindings(
        wrapperName: 'ColumnarDecompressBindings',
      ),
      preamble: '''
// Generated by package:ffigen. Do not edit manually.
// ODBC Fast contributors. MIT license; see LICENSE.
// Regenerate: dart run tool/ffigen.dart [absolute libclang path]
// ignore_for_file: type=lint
''',
    ),
  ).generate(libclangDylib: args.isEmpty ? null : Uri.file(args.single));
}
