// Generated by package:ffigen. Do not edit manually.
// ODBC Fast contributors. MIT license; see LICENSE.
// Regenerate: dart run tool/ffigen.dart [absolute libclang path]
// ignore_for_file: type=lint

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
import 'dart:ffi' as ffi;

class ColumnarDecompressBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  ColumnarDecompressBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  ColumnarDecompressBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Decompress a single columnar column payload. On success, returns 0; `*out` points to
  /// memory allocated by this library and `*out_len` / `*out_cap` are set. Call
  /// [odbc_columnar_decompress_free] with the same `out`, `out_len`, and `out_cap` to release.
  /// Lengths are `u32` to match a plain Dart/FFI binding without `size_t` porting.
  int odbc_columnar_decompress(
    int aAlgorithm,
    ffi.Pointer<ffi.Uint8> aData,
    int aDataLen,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> aOutData,
    ffi.Pointer<ffi.UnsignedInt> aOutLen,
    ffi.Pointer<ffi.UnsignedInt> aOutCap,
  ) {
    return _odbc_columnar_decompress(
      aAlgorithm,
      aData,
      aDataLen,
      aOutData,
      aOutLen,
      aOutCap,
    );
  }

  late final _odbc_columnar_decompressPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.UnsignedChar,
              ffi.Pointer<ffi.Uint8>,
              ffi.UnsignedInt,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
              ffi.Pointer<ffi.UnsignedInt>,
              ffi.Pointer<ffi.UnsignedInt>)>>('odbc_columnar_decompress');
  late final _odbc_columnar_decompress =
      _odbc_columnar_decompressPtr.asFunction<
          int Function(
              int,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
              ffi.Pointer<ffi.UnsignedInt>,
              ffi.Pointer<ffi.UnsignedInt>)>();

  /// Frees a buffer returned by [odbc_columnar_decompress].
  void odbc_columnar_decompress_free(
    ffi.Pointer<ffi.Uint8> aP,
    int aLen,
    int aCap,
  ) {
    return _odbc_columnar_decompress_free(
      aP,
      aLen,
      aCap,
    );
  }

  late final _odbc_columnar_decompress_freePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.UnsignedInt,
              ffi.UnsignedInt)>>('odbc_columnar_decompress_free');
  late final _odbc_columnar_decompress_free = _odbc_columnar_decompress_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Uint8>, int, int)>();

  /// NativeFinalizer callback. The allocation registry owns the buffer layout;
  /// this entry point may run on a GC thread and never calls into Dart.
  void odbc_columnar_decompress_release(
    ffi.Pointer<ffi.Void> aPointer,
  ) {
    return _odbc_columnar_decompress_release(
      aPointer,
    );
  }

  late final _odbc_columnar_decompress_releasePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'odbc_columnar_decompress_release');
  late final _odbc_columnar_decompress_release =
      _odbc_columnar_decompress_releasePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  /// Diagnostic count of buffers still owned by the decompression registry.
  /// A poisoned registry never reports a successful zero snapshot.
  int odbc_columnar_decompress_allocation_count() {
    return _odbc_columnar_decompress_allocation_count();
  }

  late final _odbc_columnar_decompress_allocation_countPtr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function()>>(
          'odbc_columnar_decompress_allocation_count');
  late final _odbc_columnar_decompress_allocation_count =
      _odbc_columnar_decompress_allocation_countPtr
          .asFunction<int Function()>();

  late final addresses = _SymbolAddresses(this);
}

class _SymbolAddresses {
  final ColumnarDecompressBindings _library;
  _SymbolAddresses(this._library);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>
      get odbc_columnar_decompress_release =>
          _library._odbc_columnar_decompress_releasePtr;
}
