# Quick build status check
$env:Path += ";$env:USERPROFILE\.cargo\bin"

Write-Host "=== Build Status Check ===" -ForegroundColor Cyan
Write-Host ""

# Check Rust library
Write-Host "Rust Library:" -ForegroundColor Yellow
$dllPath = "native\target\release\odbc_engine.dll"
$libPath = "native\target\release\odbc_engine.dll.lib"
$pdbPath = "native\target\release\odbc_engine.pdb"
$expPath = "native\target\release\odbc_engine.dll.exp"
if (Test-Path $dllPath) {
    $size = (Get-Item $dllPath).Length / 1MB
    Write-Host "  [OK] odbc_engine.dll ($([math]::Round($size, 2)) MB)" -ForegroundColor Green
    if (Test-Path $libPath) { Write-Host "  [OK] odbc_engine.dll.lib" -ForegroundColor Green }
    if (Test-Path $pdbPath) { Write-Host "  [OK] odbc_engine.pdb" -ForegroundColor Green }
    if (Test-Path $expPath) { Write-Host "  [OK] odbc_engine.dll.exp" -ForegroundColor Green }
} else {
    Write-Host "  [MISSING] odbc_engine.dll" -ForegroundColor Red
    Write-Host "    Hint: run 'cargo build --release' in native/odbc_engine" -ForegroundColor Gray
}

Write-Host ""

# Check C header
Write-Host "C Header:" -ForegroundColor Yellow
$headerPath = "native\odbc_engine\include\odbc_engine.h"
if (Test-Path $headerPath) {
    Write-Host "  [OK] odbc_engine.h" -ForegroundColor Green
} else {
    Write-Host "  [MISSING] odbc_engine.h" -ForegroundColor Red
    Write-Host "    Hint: header is generated by cbindgen during Rust build" -ForegroundColor Gray
}

Write-Host ""

# Check Dart bindings
Write-Host "Dart Bindings:" -ForegroundColor Yellow
$bindingsPath = "lib\infrastructure\native\bindings\odbc_bindings.dart"
if (Test-Path $bindingsPath) {
    Write-Host "  [OK] odbc_bindings.dart" -ForegroundColor Green
} else {
    Write-Host "  [MISSING] odbc_bindings.dart" -ForegroundColor Red
}

Write-Host ""
Write-Host "=== Summary ===" -ForegroundColor Cyan
Write-Host "Rust installed: YES" -ForegroundColor Green

$rustOk = Test-Path $dllPath
$headerOk = Test-Path $headerPath
$bindingsOk = Test-Path $bindingsPath

Write-Host ("Rust build: " + ($(if ($rustOk) { "OK" } else { "FAILED" }))) -ForegroundColor $(if ($rustOk) { "Green" } else { "Red" })
Write-Host ("C header: " + ($(if ($headerOk) { "OK" } else { "MISSING" }))) -ForegroundColor $(if ($headerOk) { "Green" } else { "Red" })
Write-Host ("Dart bindings: " + ($(if ($bindingsOk) { "OK" } else { "MISSING" }))) -ForegroundColor $(if ($bindingsOk) { "Green" } else { "Red" })
Write-Host ""

Write-Host "Next:" -ForegroundColor Yellow
Write-Host "  - If bindings generation fails, install LLVM/Clang (ffigen requires libclang)." -ForegroundColor Yellow
