#!/usr/bin/env python3
"""
ODBC Fast - Project Cleanup Analyzer
Identifies duplicate, obsolete, or unnecessary files in the project.

Usage:
    python scripts/cleanup.py
    python scripts/cleanup.py --dry-run
    python scripts/cleanup.py --execute
"""

import argparse
import hashlib
import os
import sys
from pathlib import Path
from typing import Dict, List, Set


class Colors:
    CYAN = "\033[96m"
    YELLOW = "\033[93m"
    GREEN = "\033[92m"
    RED = "\033[91m"
    GRAY = "\033[90m"
    RESET = "\033[0m"

    @staticmethod
    def colorize(text: str, color: str) -> str:
        if sys.stdout.isatty():
            return f"{color}{text}{Colors.RESET}"
        return text


def print_header(text: str):
    print(Colors.colorize(text, Colors.CYAN))


def print_section(text: str):
    print(Colors.colorize(text, Colors.YELLOW))


def print_success(text: str):
    print(Colors.colorize(text, Colors.GREEN))


def print_warning(text: str):
    print(Colors.colorize(text, Colors.YELLOW))


def print_error(text: str):
    print(Colors.colorize(text, Colors.RED))


def print_info(text: str):
    print(Colors.colorize(text, Colors.GRAY))


def get_file_hash(path: Path) -> str:
    """Calculate SHA256 hash of a file."""
    sha256 = hashlib.sha256()
    try:
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(8192), b""):
                sha256.update(chunk)
        return sha256.hexdigest()
    except Exception:
        return ""


def find_duplicates(root: Path, patterns: List[str]) -> Dict[str, List[Path]]:
    """Find duplicate files by content hash."""
    hash_map: Dict[str, List[Path]] = {}
    
    for pattern in patterns:
        for file_path in root.rglob(pattern):
            if file_path.is_file():
                file_hash = get_file_hash(file_path)
                if file_hash:
                    if file_hash not in hash_map:
                        hash_map[file_hash] = []
                    hash_map[file_hash].append(file_path)
    
    # Keep only duplicates (2+ files with same hash)
    return {k: v for k, v in hash_map.items() if len(v) > 1}


def find_generated_api_docs(root: Path) -> List[Path]:
    """Find generated API documentation directories."""
    candidates = []
    
    # doc/api is typically generated by dartdoc
    api_doc = root / "doc" / "api"
    if api_doc.exists() and api_doc.is_dir():
        candidates.append(api_doc)
    
    return candidates


def find_coverage_reports(root: Path) -> List[Path]:
    """Find coverage report directories."""
    candidates = []
    
    for coverage_dir in ["coverage", "native/coverage"]:
        path = root / coverage_dir
        if path.exists() and path.is_dir():
            candidates.append(path)
    
    return candidates


def format_size(size_bytes: int) -> str:
    """Format file size in human-readable format."""
    for unit in ["B", "KB", "MB", "GB"]:
        if size_bytes < 1024.0:
            return f"{size_bytes:.1f} {unit}"
        size_bytes /= 1024.0
    return f"{size_bytes:.1f} TB"


def get_dir_size(path: Path) -> int:
    """Calculate total size of a directory."""
    total = 0
    try:
        for item in path.rglob("*"):
            if item.is_file():
                total += item.stat().st_size
    except Exception:
        pass
    return total


def analyze_project(root: Path) -> dict:
    """Analyze project and return findings."""
    findings = {
        "duplicates": {},
        "generated_docs": [],
        "coverage": [],
        "safe_to_remove": []
    }
    
    # Find duplicate README files
    print_info("  Scanning for duplicate files...")
    findings["duplicates"] = find_duplicates(root, ["README.md", "*.mdc", "*.md"])
    
    # Find generated docs
    print_info("  Scanning for generated documentation...")
    findings["generated_docs"] = find_generated_api_docs(root)
    
    # Find coverage reports
    print_info("  Scanning for coverage reports...")
    findings["coverage"] = find_coverage_reports(root)
    
    # Check for safe-to-remove items
    safe_patterns = [
        "**/*.log",
        "**/*.tmp",
        "**/*.temp",
        "**/*.bak",
        "**/*.backup",
        "**/.DS_Store",
        "**/Thumbs.db",
        "**/desktop.ini",
    ]
    
    print_info("  Scanning for temporary files...")
    for pattern in safe_patterns:
        for file_path in root.rglob(pattern):
            if file_path.is_file():
                findings["safe_to_remove"].append(file_path)
    
    return findings


def print_findings(root: Path, findings: dict):
    """Print analysis findings."""
    print()
    print_header("=== Project Cleanup Analysis ===")
    print()
    
    # Duplicates
    if findings["duplicates"]:
        print_section("[*] Duplicate Files (by content):")
        print()
        for file_hash, files in findings["duplicates"].items():
            if len(files) > 1:
                print(f"  Hash: {file_hash[:16]}...")
                for file_path in files:
                    rel_path = file_path.relative_to(root)
                    size = format_size(file_path.stat().st_size)
                    print_info(f"    - {rel_path} ({size})")
                print()
    else:
        print_success("[OK] No duplicate files found")
        print()
    
    # Generated docs
    if findings["generated_docs"]:
        print_section("[DOCS] Generated Documentation (can be regenerated):")
        print()
        for doc_dir in findings["generated_docs"]:
            rel_path = doc_dir.relative_to(root)
            size = format_size(get_dir_size(doc_dir))
            print_info(f"  - {rel_path}/ ({size})")
        print()
    else:
        print_success("[OK] No generated docs found")
        print()
    
    # Coverage reports
    if findings["coverage"]:
        print_section("[COV] Coverage Reports (can be regenerated):")
        print()
        for cov_dir in findings["coverage"]:
            rel_path = cov_dir.relative_to(root)
            size = format_size(get_dir_size(cov_dir))
            print_info(f"  - {rel_path}/ ({size})")
        print()
    else:
        print_success("[OK] No coverage reports found")
        print()
    
    # Safe to remove
    if findings["safe_to_remove"]:
        print_section("[TEMP] Temporary Files (safe to remove):")
        print()
        total_size = sum(f.stat().st_size for f in findings["safe_to_remove"])
        for file_path in findings["safe_to_remove"][:10]:
            rel_path = file_path.relative_to(root)
            size = format_size(file_path.stat().st_size)
            print_info(f"  - {rel_path} ({size})")
        
        if len(findings["safe_to_remove"]) > 10:
            remaining = len(findings["safe_to_remove"]) - 10
            print_info(f"  ... and {remaining} more files")
        
        print()
        print_info(f"  Total: {len(findings['safe_to_remove'])} files ({format_size(total_size)})")
        print()
    else:
        print_success("[OK] No temporary files found")
        print()


def execute_cleanup(root: Path, findings: dict):
    """Execute cleanup operations."""
    import shutil
    
    print_header("=== Executing Cleanup ===")
    print()
    
    removed_count = 0
    total_size = 0
    
    # Remove generated docs
    for doc_dir in findings["generated_docs"]:
        try:
            size = get_dir_size(doc_dir)
            shutil.rmtree(doc_dir)
            rel_path = doc_dir.relative_to(root)
            print_success(f"[OK] Removed {rel_path}/ ({format_size(size)})")
            removed_count += 1
            total_size += size
        except Exception as e:
            rel_path = doc_dir.relative_to(root)
            print_error(f"[FAIL] Failed to remove {rel_path}/: {e}")
    
    # Remove coverage reports
    for cov_dir in findings["coverage"]:
        try:
            size = get_dir_size(cov_dir)
            shutil.rmtree(cov_dir)
            rel_path = cov_dir.relative_to(root)
            print_success(f"[OK] Removed {rel_path}/ ({format_size(size)})")
            removed_count += 1
            total_size += size
        except Exception as e:
            rel_path = cov_dir.relative_to(root)
            print_error(f"[FAIL] Failed to remove {rel_path}/: {e}")
    
    # Remove temporary files
    for file_path in findings["safe_to_remove"]:
        try:
            size = file_path.stat().st_size
            file_path.unlink()
            removed_count += 1
            total_size += size
        except Exception as e:
            rel_path = file_path.relative_to(root)
            print_error(f"[FAIL] Failed to remove {rel_path}: {e}")
    
    print()
    print_success(f"Cleaned up {removed_count} items, freed {format_size(total_size)}")
    print()


def main():
    parser = argparse.ArgumentParser(
        description="Analyze and clean up unnecessary files in the project"
    )
    parser.add_argument(
        "--execute",
        action="store_true",
        help="Execute cleanup (remove files). Default is dry-run (analyze only).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Analyze only, do not remove files (default behavior).",
    )
    args = parser.parse_args()

    root_dir = Path(__file__).parent.parent
    os.chdir(root_dir)

    print_header("=== ODBC Fast - Project Cleanup ===")
    print()
    
    if args.execute:
        print_warning("WARNING: EXECUTE MODE: Files will be removed!")
    else:
        print_info("INFO: DRY-RUN MODE: No files will be removed (use --execute to clean)")
    
    print()
    print_info("Analyzing project...")
    
    findings = analyze_project(root_dir)
    print_findings(root_dir, findings)
    
    if args.execute:
        # Ask for confirmation
        response = input("Are you sure you want to proceed with cleanup? (yes/no): ").strip().lower()
        if response in ("yes", "y"):
            execute_cleanup(root_dir, findings)
        else:
            print_warning("Cleanup cancelled.")
            return 1
    else:
        print_section("[TIPS] Recommendations:")
        print()
        if findings["generated_docs"]:
            print_info("  - Generated docs can be removed (dart doc will regenerate)")
        if findings["coverage"]:
            print_info("  - Coverage reports can be removed (tarpaulin will regenerate)")
        if findings["safe_to_remove"]:
            print_info("  - Temporary files are safe to remove")
        if findings["duplicates"]:
            print_info("  - Review duplicate files manually")
        print()
        print_info("  Run with --execute to perform cleanup")
        print()
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
